spring:
 
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true 
     
hystrix:
  threadpool:
    default:
      coreSize: 1000
      execution:
        timeout: 
          enabled: true
        isolation:
          thread: 
            timeoutInMilliseconds: 60000
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000
          semaphore:
            maxConcurrentRequests: 1000  
      fallback: 
        isolation:
          semaphore: 
            maxConcurrentRequests: 1000      
    circuitBreaker:
      requestVolumeThreshold: 1000        

        
ribbon: 
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false     
  httpclient: 
    enabled: false
  okhttp: 
    enabled: true    
    
    
feign:
  hystrix:
    enabled: true 
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
  response: 
    enabled: true
  httpclient:  
    enabled: false
  okhttp: 
    enabled: true   
  
custom:
  incloudname: devcloud
      
  

          
          
          
             