spring:
  application:
    name: mmj-cloud-elasticsearch

  data:
    elasticsearch:
      cluster-nodes: 192.168.1.25:9300,192.168.1.25:9301,192.168.1.25:9302
      cluster-name: elasticsearch

  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true

  redis:
    cluster:
      nodes:
      - 192.168.1.21:7010
      - 192.168.1.21:7011
      - 192.168.1.21:7012
      - 192.168.1.21:7013
      - 192.168.1.21:7014
      - 192.168.1.21:7015
    password: mmj1234
    timeout: 20000
    pool:
      max-active: 100
      min-idle: 1
      max-idle: 10
      max-wait: -1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
      master:
        name: master
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.20:3306/mmj-dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
        username: root
        password: mmj1234
      slave:
        name: slave
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.20:3306/mmj-dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
        username: root
        password: mmj1234

  kafka:
    bootstrap-servers: 192.168.1.20:9091,192.168.1.20:9092,192.168.1.20:9093
    producer:
      batch-size: 16
      retries: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: elasticsearchgroup

security:
  basic:
    enabled: false

hystrix:
  threadpool:
    default:
      coreSize: 1000
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 180000
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000
          semaphore:
            maxConcurrentRequests: 1000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
    circuitBreaker:
      requestVolumeThreshold: 1000


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
  response:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
