spring:

  application:
    name: mmj-cloud-active

  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true

  redis:
    cluster:
      nodes:
      - 121.40.83.80:7010
      - 121.40.83.80:7011
      - 121.40.83.80:7012
      - 121.40.83.80:7013
      - 121.40.83.80:7014
      - 121.40.83.80:7015
    password: mX66TGIwntkFHJzC
    timeout: 20000
    pool:
      max-active: 100
      min-idle: 1
      max-idle: 10
      max-wait: -1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
      master:
        name: master
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://118.31.15.139:3306/mmj?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
        username: root
        password: mX66TGIwntkFHJzC
      slave:
        name: slave
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://118.31.15.139:3306/mmj?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
        username: root
        password: mX66TGIwntkFHJzC

  kafka:
    bootstrap-servers: 192.168.1.20:9091,192.168.1.20:9092,192.168.1.20:9093
    producer:
      batch-size: 16
      retries: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: activegroup

security:
  basic:
    enabled: false


hystrix:
  threadpool:
    default:
      coreSize: 1000
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 180000
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 240000
          semaphore:
            maxConcurrentRequests: 1000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
    circuitBreaker:
      requestVolumeThreshold: 1000


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ServerListRefreshInterval: 5000
  httpclient:
    enabled: false
  okhttp:
    enabled: true


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
  response:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

redisson:
  value: '{"clusterServersConfig":{"idleConnectionTimeout":10000,"pingTimeout":1000,"connectTimeout":10000,"timeout":3000,"retryAttempts":3,"retryInterval":1500,"reconnectionTimeout":3000,"failedSlaveReconnectionInterval":3000,"failedSlaveCheckInterval":60000,"failedAttempts":3,"password":"mmj1234","subscriptionsPerConnection":5,"clientName":"orderClient","loadBalancer":{"class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"},"subscriptionConnectionMinimumIdleSize":1,"subscriptionConnectionPoolSize":50,"slaveConnectionMinimumIdleSize":32,"slaveConnectionPoolSize":64,"masterConnectionMinimumIdleSize":32,"masterConnectionPoolSize":64,"readMode":"SLAVE","subscriptionMode":"SLAVE","nodeAddresses":["redis://192.168.1.21:7010","redis://192.168.1.21:7011","redis://192.168.1.21:7012","redis://192.168.1.21:7013","redis://192.168.1.21:7014","redis://192.168.1.21:7015"],"scanInterval":1000,"pingConnectionInterval":0,"keepAlive":false,"tcpNoDelay":false},"threads":16,"nettyThreads":32,"codec":{"class":"org.redisson.codec.FstCodec"},"transportMode":"NIO"}'

weChatTmpId:
  minAppid: wxca855317c075f407 #wx7a01aef90c714fe2
  officialAppid: wxade5b7db33565f27 #wx77a4d1dccaab522c
  seckillBook: GgRGAmap6oGz45XB4MF_COZe6A69W7Gd_I76VL9EBPw #dD0Sr0cc26Px0tEqCzCqiDT094QBJWXMfxVA1qE3OdY
  cutBook: GZ4HNPleXU0lfEpvcxKnjc5Cg9XCVjyjnToh6bZaJl8 #dqwXbvAHzGJrhsYHqM9JGrU3PoOfrLBjhHSncFpyzWI
  lotteryOpenBook: GZ4HNPleXU0lfEpvcxKnjc5Cg9XCVjyjnToh6bZaJl8 #dqwXbvAHzGJrhsYHqM9JGrU3PoOfrLBjhHSncFpyzWI
  lotteryPublicBook: GZ4HNPleXU0lfEpvcxKnjc5Cg9XCVjyjnToh6bZaJl8 #dqwXbvAHzGJrhsYHqM9JGrU3PoOfrLBjhHSncFpyzWI
  lotteryCouponBook: YKoi-OWnCzHOlV7cvq5XhP_gHyeUK8SVUm8RL81Blz8 #YLaLnBAom7JkW8GJNSiAz-tRnml0lB8-iSM4tBNTflU
  prizewheelsSignBook: GZ4HNPleXU0lfEpvcxKnjc5Cg9XCVjyjnToh6bZaJl8 #dqwXbvAHzGJrhsYHqM9JGrU3PoOfrLBjhHSncFpyzWI
  prizewheelsTenBook: GZ4HNPleXU0lfEpvcxKnjc5Cg9XCVjyjnToh6bZaJl8 #dqwXbvAHzGJrhsYHqM9JGrU3PoOfrLBjhHSncFpyzWI
  tenSaleBook: GUNhIhXdH3F1fFDvpzQeQoluaSAqHQJ8spXarqUjwHQ #fQgyv0-Ysm4H1ies_pdSj5tFFyE_2f7_mfkkPKFKCPc
  signBook: GZ4HNPleXU0lfEpvcxKnjc5Cg9XCVjyjnToh6bZaJl8 #dqwXbvAHzGJrhsYHqM9JGrU3PoOfrLBjhHSncFpyzWI
  signDoubleBook: g9fRQVUynEenYc_tcXxodJoGYCdsbeDfrfusgFb6mIE #5OMDphiixvGXE-mDFdQ_IvN9wRvM9rgh4LKfwg259jU
  orderExpressBook: GZ4HNPleXU0lfEpvcxKnjc5Cg9XCVjyjnToh6bZaJl8 #dqwXbvAHzGJrhsYHqM9JGrU3PoOfrLBjhHSncFpyzWI
  seckillAfterOpen: GgRGAmap6oGz45XB4MF_COZe6A69W7Gd_I76VL9EBPw #dD0Sr0cc26Px0tEqCzCqiDT094QBJWXMfxVA1qE3OdY
  cutAfterHelp: fqEH0hj36Br64xvgdF7RlEhTaqJXmfbls3pv2gC9wdk #eDiNkIuw8jnMjFwOTifY3h-QL4rqq3wNYRufaYlEySo
  lotteryAfterOnceWeek: TcQoRpbSsdO0OZtR3ODTittQtC9JaOx4rRDi1hb9XtE #6KWouF1P-L8vwpRx2Zd-fAlV7RhJ4hnuG4mF3tZdaJU
  lotteryAfterOpen: TcQoRpbSsdO0OZtR3ODTittQtC9JaOx4rRDi1hb9XtE #6KWouF1P-L8vwpRx2Zd-fAlV7RhJ4hnuG4mF3tZdaJU
  prizewheelsAfterRemind: z7o_c3W-xovare0GzymvVlSGPKbePybYGOfarn5_EkY #IDP5aMSYDhYBjLYRUS0Gug9wx0n1mvDYQBsx5bgX9tg
  tenAfterRefresh: GZ4HNPleXU0lfEpvcxKnjc5Cg9XCVjyjnToh6bZaJl8 #dqwXbvAHzGJrhsYHqM9JGrU3PoOfrLBjhHSncFpyzWI
  signAfterRemind: z7o_c3W-xovare0GzymvVlSGPKbePybYGOfarn5_EkY #IDP5aMSYDhYBjLYRUS0Gug9wx0n1mvDYQBsx5bgX9tg
  signAfterHelp: g9fRQVUynEenYc_tcXxodJoGYCdsbeDfrfusgFb6mIE #5OMDphiixvGXE-mDFdQ_IvN9wRvM9rgh4LKfwg259jU
  orderAfterExpressRefresh: 54deci1A1zG5ui6qpyzhBZix7RFOYMJFtaPRyWhLpzc #M-bLRcbeFh9VwxNoyqsIvA1XqAGxFA1GOMFmNziFulg