server:
  port: 8761

spring:
  application:
    name: mmj-cloud-eureka
    
security:
  basic:
    enabled: true
  user:
    name: mmj
    password: mmj    
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://mmj:mmj@service-eureka-1:8761/eureka/,http://mmj:mmj@service-eureka-2:8761/eureka/
  instance:
    hostname: service-eureka-0
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  server:  
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    use-read-only-response-cache: false
    